### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by meneer** [LoranKloeze/zelftestgedaan.nl#4]
![details](https://user-images.githubusercontent.com/1175741/145255326-7ae88637-a133-40e6-8f80-ae2a0d6a1519.gif)

**Comment by LoranKloeze** [comment]
Eerste punt: helaas ondersteunt Heroku nog geen ipv6...
Derde punt: opgelost want zelftestgedaan.nl resolved nu ook goed
Vierde punt: Rails heeft standaard CSP uitstaan, staat nu aan
🚀🚀🚀
